### ISSUE TITLE
Danish lang.

### ISSUE THREAD

**Issue by Ylacat** [strongbox-password-safe/babel#225]
I wish to translate the project to Danish.

**Comment by strongbox-mark** [comment]
Hi @Ylacat - That would be great, could you drop an email to support@strongboxsafe.com and I'll get you setup in the system. :)

**Comment by comradekingu** [comment]
@Ylacat Invited you to https://hosted.weblate.org/projects/strongbox/
Look for an e-mail about it.

**Comment by Ylacat** [comment]
> 
> 
> @Ylacat Invited you to https://hosted.weblate.org/projects/strongbox/
> Look for an e-mail about it.

I find it odd to receive 2 invites, plus i understand the willingness to help. But this is the wrong way.
