### ISSUE TITLE
Italian translation support

### ISSUE THREAD

**Issue by markoer73** [strongbox-password-safe/babel#69]
Hi Mark, I would be very happy to take on the Italian translation.

My name is already the Italian translation of your name, by the way :-) so it's perfect...

Cheers, Marco.

PS. I am already a paying user of both your IOS and Mac app :-) (and my wife needs both of them, therefore it is imperative I translate!...)

**Comment by mmcguill** [comment]
Hi Marco, that's awesome, thank you so much... could you drop me a mail and I can add you to the system :) mark@strongboxsafe.com will get me. Ciao and Grazie!

**Comment by mmcguill** [comment]
@markoer73 - let me know if you have any trouble reaching me on that email? you can also get me on mark.mcguill@gmail.com
